# general settings
name: IET-light-x3
model_type: IETModel
scale: 3
num_gpu: 10
manual_seed: 0
# find_unused_parameters: True

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_train_HR
    dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic/X3
    filename_tmpl: '{}x3'
    io_backend:
      type: disk

    gt_size: 234
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 14
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: True
    persistent_workers: True

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/TestDataSR/HR/Set5/x3
    dataroot_lq: datasets/TestDataSR/LR/LRBI/Set5/x3
    io_backend:
      type: disk

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/TestDataSR/HR/Set14/x3
    dataroot_lq: datasets/TestDataSR/LR/LRBI/Set14/x3
    io_backend:
      type: disk

  val_3:
    name: BSD100
    type: PairedImageDataset
    dataroot_gt: datasets/TestDataSR/HR/B100/x3
    dataroot_lq: datasets/TestDataSR/LR/LRBI/B100/x3
    io_backend:
      type: disk

  val_4:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: datasets/TestDataSR/HR/Urban100/x3
    dataroot_lq: datasets/TestDataSR/LR/LRBI/Urban100/x3
    io_backend:
      type: disk

  val_5:
    name: Manga109
    type: PairedImageDataset
    dataroot_gt: datasets/TestDataSR/HR/Manga109/x3
    dataroot_lq: datasets/TestDataSR/LR/LRBI/Manga109/x3
    io_backend:
      type: disk

# network structures
network_g:
  type: IET
  nattn_dim: 60
  topk_focus: [[914, 225, 225], [345, 225, 125], [225, 125, 125], [185, 81, 81], [121, 81, 81], [64, 64, 64], [36, 36, 36], [36, 36, 36]]
  topk_prop_1: [22, 20, 14, 12, 0, 0, 0, 0]
  topk_prop_2: [12, 11, 9, 8, 0, 0, 0, 0]
  topk_prop_3: [120, 100, 60, 40, 0, 0, 0, 0]
  upscale: 3
  in_chans: 3
  img_size: 78
  embed_dim: 54
  depths: [3, 3, 3, 3, 3, 3, 3, 3, ]
  num_heads: 3
  local_range: 17
  sparse_range: 25
  dilation: 3
  convffn_kernel_size: 7
  img_range: 1.
  mlp_ratio: 1
  upsampler: 'pixelshuffledirect'
  resi_connection: '1conv'
  use_checkpoint: false

# path
path:
  pretrain_network_g: experiments/pretrained_models/IET-SR-light-x2.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Muon
    lr: !!float 5e-4
    weight_decay: 0.001
    betas: [0.9, 0.99]
    scale: 6

  scheduler:
    type: MultiStepLR
    milestones: [25000, 40000, 50000, 60000]
    gamma: 0.5

  total_iter: 250000
  warmup_iter: 10000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 3
      test_y_channel: yes

    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 3
      test_y_channel: yes

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
